name: update-flake-lock
run-name: Update nix flake
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Nix
        uses: https://git.lazylab.casa/lazyload/nix-installer-action@v10

      - name: Update flake.lock
        run: nix flake update

      - name: Commit
        uses: https://git.lazylab.casa/lazyload/git-auto-commit-action@v5
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: lazybot
          commit_user_name: lazybot@lazyloading.net
          commit_author: lazybot <lazybot@lazyloading.net>
          skip_dirty_check: false
          skip_fetch: true
